name: text_emotion_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==3.8.0
      - scikit-learn==1.6.1
      - pandas==2.2.2
      - numpy==2.0.2
      - matplotlib==3.10.0
      - seaborn==0.13.2  # versi terbaru compatible dengan Python 3.12
      - joblib
      - scipy
      - tensorflow
      - torch
